### ISSUE TITLE
Searchable registry of issuer's certificates

### ISSUE THREAD

**Issue by 0xturboblitz** [zk-passport/openpassport#110]
We should have a searchable registry like [archive.prove.email](https://archive.prove.email/) that displays all certificates and their metadata, like the signature algorithm they use and their validity period. It could also say if they are supported right now in proof of passport.

It could contain both the levels of certificates (CSCAs and DSCs). The data sources are [here](https://github.com/zk-passport/proof-of-passport/blob/dev/registry/outputs/csca_formatted.json) and [here](https://github.com/zk-passport/proof-of-passport/blob/dev/registry/outputs/dsc_formatted.json).

This would also be very useful to other teams working on passports verification in zk.

**Comment by BlackStarkGoku** [comment]
Hello, I want to help, I don't understand well yet what is asked, but I will go through the project to try to understand and will ask you question If needed

**Comment by martinvibes** [comment]
can i hop on this @0xturboblitz

**Comment by Adecom16** [comment]
can i work on this @0xturboblitz

**Comment by 0xturboblitz** [comment]
Hi, please talk about your experience and explain how you plan on tackling this problem

**Comment by od-hunter** [comment]
Can I be assigned this please

**Comment by od-hunter** [comment]
I’m new to Starknet ecosystem and I’ll love to contribute.

**Comment by Shoetan** [comment]
@0xturboblitz  I am Emmanuel a software developer. I think the below steps can be employed to achieve this 

## Tasks

### 1. Gathering Data
- [ ] Collect CSCA/DSC from various sources:
  - ICAO
  - Germany
  - Italy
- [ ] Verify all data to ensure accuracy.

### 2. Designing the Database
- [ ] Store DSCAs and CSCAs, along with their metadata.
- [ ] Create a schema that includes necessary fields for certificates and their metadata.
- [ ] Ensure the database supports efficient key search and access.

### 3. Building the Backend
- [ ] Create an API to:
  - Add certificates
  - Update certificates
  - Get certificates
- [ ] Implement security checks to maintain the integrity of certificates.

### 4. Creating the Frontend
- [ ] Develop a user interface for searching and displaying certificates.
- [ ] Ensure the interface allows users to view metadata, especially its validity period.

**Comment by od-hunter** [comment]
@0xturboblitz hello, if I’m given this issue, below is how I intend on tackling this issue:

1. Requirements Gathering, that is understanding the Current System, identify additional Sources of CSCAs and DSCs, such as those from Germany, Italy, and other relevant countries.
2. Design the Registry (a data model to store the CSCAs and DSCs.
3. Data Collection and Integration

4. Backend Development, that is I’ll design a RESTful API to interact with the registry. Define endpoints for:
   - Adding new certificates
   - Updating certificates
   - Searching certificates by various criteria (country, type, validity period, etc.)
   - Retrieving certificate details
5. Frontend Development, I’ll design a user-friendly interface.
6. Please I’d like to be given this opportunity.

**Comment by 0xturboblitz** [comment]
to assign this issue to anyone I will need a message presenting how the issue can be tackled that is not GPT generated

**Comment by Adecom16** [comment]
> Hi, please talk about your experience and explain how you plan on tackling this problem
I am a smart contract developer and also i have tackle this problem before in one of my project to tackle this problem here are the solutions

1. Thoroughly understand the existing ICAO standards and PKI system for electronic passports.
2. Gather requirements from stakeholders like government agencies and security expert.
3. Define a data model and schema to store CSCAs, DSCs, and metadata from various sources.
4. Develop a secure backend system and database to manage the registry data.
5. Implementing a user-friendly frontend with search and browsing capabilities similar to https://archive.prove.email/.
6. Establish processes for data collection, verification, and submission from trusted source.
7. Conduct thorough testing and deploy the system securely.

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/proof-of-passport).

### My background and how it can be leveraged
I have experience in implementing solutions. I currently work as a director and developer in my own startup

### How I plan on tackling this issue
It would be a pleasure to contribute to this issue, I have all the desire to work hard on this. I divide my work into 3 points that are repeated in a loop until the expected result is achieved.
1. investigate if it is possible to use a library like ss-search or something similar. It will depend on the previous research or if required, unique functions would be created from scratch.
2. Implement after the previous research to do the first tests locally.
3. Receive feedback to improve my code.

I hope they accept me, it's my first ODhack

**Comment by 0xturboblitz** [comment]
Assigned you @MPSxDev, please keep us updated soon here or on telegram

**Comment by MPSxDev** [comment]
### First results
I've already been working on a search engine similar to archive.prove.email where the input can be:

1. Any country code.
2. Any metadata such as "signature_algorithm", "hash_algorithm", "curve_exponent", "bit_length"

For example, if I enter "es" it would give me all the metadata for everything corresponding to that country.
All search logic is working without problems.

Here I leave an example image for the case of csca_formatted
![image](https://github.com/user-attachments/assets/ca3e52a9-7b37-4fb0-926c-5b1a72550b7c)


It was implemented using React. I don't know if it works or requires implementation in another language.

I have a question, will this search engine be implemented separately, or will it be included in some other component?

**Comment by remicolin** [comment]
hi @MPSxDev the search engine will be implemented as a new page on [proofofpassport.com](https://github.com/zk-passport/proofofpassport.com)

feel free to dm @colinremi on tg in case you have questions

**Comment by MPSxDev** [comment]
Thank you very much for your reply. I will be working on this. If I have any questions, I will let you know.

**Comment by 0xturboblitz** [comment]
Solve here https://github.com/zk-passport/openpassport.app/pull/5
